# Generated by Django 2.2.24 on 2021-11-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liquid', models.DecimalField(decimal_places=2, max_digits=100)),
                ('oil', models.DecimalField(decimal_places=2, max_digits=100)),
                ('water', models.DecimalField(decimal_places=2, max_digits=100)),
                ('wct', models.DecimalField(decimal_places=2, max_digits=100)),
                ('calc_status', models.IntegerField(choices=[(1, 'завершен'), (2, 'идет расчет'), (3, 'в очереди')])),
                ('calc_duration', models.DurationField()),
            ],
        ),
    ]
